//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetAPI_News
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projigEntities1 : DbContext
    {
        public projigEntities1()
            : base("server=localhost;user id=root;database=projig;port=3307")
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_article> t_articles { get; set; }
        public virtual DbSet<t_categorie> t_categories { get; set; }
        public virtual DbSet<t_user> t_users { get; set; }
    }
}
